#!/usr/bin/env python3
"""
=================================================================
 gen_checksum.py  -  Build-time kernel integrity checksum tool
=================================================================
Computes the checksum that boot/stage2.asm will recompute at boot
time and compare against, seeded by the random constant produced
by gen_seed.py.

The algorithm here MUST exactly match verify_checksum in
boot/stage2.asm:

    acc = seed
    for each little-endian 32-bit word `d` in the kernel image
    (zero-padded up to the reserved kernel size):
        acc = rol32(acc XOR d, 1)

This is a simple rotate/XOR checksum, not a cryptographic hash.
It is sufficient to catch accidental corruption or a swapped
kernel image, which is the threat model for this project - it is
NOT presented as cryptographically secure against a deliberate
attacker who can rewrite the disk image (that would require
signing with a real hash + asymmetric signature, which is out of
scope for this bootloader project). See docs/DOCUMENTATION.md for
a discussion of this limitation.

Outputs:
    build/checksum.bin      - 4-byte little-endian expected checksum
    build/stage2_seed.inc   - NASM include defining SEED_CONST
"""

import struct
import sys
import os


def rol32(value: int, shift: int) -> int:
    value &= 0xFFFFFFFF
    return ((value << shift) | (value >> (32 - shift))) & 0xFFFFFFFF


def compute_checksum(data: bytes, seed: int) -> int:
    if len(data) % 4 != 0:
        data = data + b"\x00" * (4 - len(data) % 4)
    acc = seed & 0xFFFFFFFF
    for i in range(0, len(data), 4):
        dword = struct.unpack_from("<I", data, i)[0]
        acc ^= dword
        acc = rol32(acc, 1)
    return acc


def main():
    if len(sys.argv) != 4:
        print("Usage: gen_checksum.py <kernel.bin> <seed.txt> <kernel_max_bytes>")
        sys.exit(1)

    kernel_path, seed_path, max_bytes_str = sys.argv[1], sys.argv[2], sys.argv[3]
    max_bytes = int(max_bytes_str)

    with open(kernel_path, "rb") as f:
        kernel_data = f.read()

    if len(kernel_data) > max_bytes:
        raise RuntimeError(
            f"Kernel ({len(kernel_data)} bytes) exceeds reserved budget "
            f"({max_bytes} bytes). Increase KERNEL_SECTORS in stage2.asm "
            f"and KERNEL_MAX_BYTES in the Makefile if the kernel grows."
        )

    padded = kernel_data + b"\x00" * (max_bytes - len(kernel_data))

    with open(seed_path) as f:
        seed = int(f.read().strip(), 16)

    checksum = compute_checksum(padded, seed)

    build_dir = os.path.dirname(os.path.abspath(kernel_path))

    checksum_path = os.path.join(build_dir, "checksum.bin")
    with open(checksum_path, "wb") as f:
        f.write(struct.pack("<I", checksum))

    inc_path = os.path.join(build_dir, "stage2_seed.inc")
    with open(inc_path, "w") as f:
        f.write(
            "; Auto-generated by tools/gen_checksum.py - do not edit by hand.\n"
            f"SEED_CONST equ 0x{seed:08X}\n"
        )

    print(f"[gen_checksum] Kernel size : {len(kernel_data)} bytes (budget {max_bytes})")
    print(f"[gen_checksum] Seed        : 0x{seed:08X}")
    print(f"[gen_checksum] Checksum    : 0x{checksum:08X}")
    print(f"[gen_checksum] Wrote {checksum_path}")
    print(f"[gen_checksum] Wrote {inc_path}")


if __name__ == "__main__":
    main()
